# Generated by Django 4.1.1 on 2022-12-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart_app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
