# Generated by Django 4.1.1 on 2022-12-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart_app', '0006_remove_review_date_time_review_date_review_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='e_cart_app.item'),
        ),
    ]
